
export const GAME_CONFIG = {
  TOTAL_POPULATION: 30,
  INITIAL_PLAYER_CASH: 100,
  TOTAL_LAND_TOKENS: 80,
  DAILY_GRAIN_NEED: 1.0,
  BREAD_SUBSTITUTE_RATIO: 0.8,
  GAME_SPEEDS: [1, 2, 5],
  TAX_RATES: {
    INCOME_LOW: 0.10,
    INCOME_MID: 0.20,
    INCOME_HIGH: 0.40,
    CORPORATE: 0.20,
    CONSUMPTION: 0.05
  }
};
